name: 'Setup k3s'
description: 'Install and configure k3s - Lightweight certified Kubernetes distribution for CI/CD'
author: 'fenio'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  version:
    description: 'k3s version to install (e.g., v1.28.5+k3s1, latest, stable, or channel like stable)'
    required: false
    default: 'stable'
  
  k3s-args:
    description: 'Additional arguments to pass to k3s installer (e.g., "--disable=traefik --disable=servicelb")'
    required: false
    default: '--write-kubeconfig-mode 644'
  
  wait-for-ready:
    description: 'Wait for k3s cluster to be ready before completing'
    required: false
    default: 'true'
  
  timeout:
    description: 'Timeout in seconds to wait for cluster readiness'
    required: false
    default: '120'
  
  dns-readiness:
    description: 'Wait for CoreDNS to be ready and verify DNS resolution works'
    required: false
    default: 'true'

outputs:
  kubeconfig:
    description: 'Path to the kubeconfig file'
    value: ${{ steps.setup.outputs.kubeconfig }}

runs:
  using: 'composite'
  steps:
    - name: Setup k3s
      id: setup
      shell: bash
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_K3S_ARGS: ${{ inputs.k3s-args }}
        INPUT_WAIT_FOR_READY: ${{ inputs.wait-for-ready }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_DNS_READINESS: ${{ inputs.dns-readiness }}
      run: ${{ github.action_path }}/setup.sh
